### ISSUE TITLE
Add second data source

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#44]
### Description

Assign yourself if you wish to work on this.

Check in with @IT2901-SINTEF01/frontend and hear what kind of visualisation they are interested in. Choose one based on feedback and points mentioned in previous issue with data sources – #15.

### Subtasks
- [x] Choose data source (comment _why_ that one)
- [x] Create POCO and GraphQL types
- [x] Mock
- [ ] Test

### Related sources
- [Entertainment while you're writing POCOs](https://www.youtube.com/watch?v=_fkdSOxE5wc)

**Comment by Kpaubert** [comment]
I suggest we use [SSB's population statistics](https://data.ssb.no/api/v0/dataset/?tags=befolkning). The three topmost give population data for the whole country, municipalities and counties, as well as data regarding the ages of the result set.

Some questions:
- Are the frontend guys on board with this, or do you suggest another data source? (@IT2901-SINTEF01/frontend)
- Would historical data be more benefitial, so that we could test out different graph types?
- Is there any way in the frontend to map the county/municipality names to places on a map?

**Comment by fredrikbw** [comment]
A similar alternative if historical data is interesting: [Befolkning. Kommuner, pr. 1.1., 1986 - siste år
](https://data.ssb.no/api/v0/dataset/26975?lang=no). Also in the JSON-stat structure.

(If you wan't to see how the data for each municipality looks like it's a bit easier to read the CSV format rather than the JSON-stat)

**Comment by FredrikAugust** [comment]
Interesting, what do you think, @IT2901-SINTEF01/frontend.

Regarding 

> (If you wan't to see how the data for each municipality looks like it's a bit easier to read the CSV format rather than the JSON-stat)

You may also open CSV files with Excel (or Numbers on Mac, Google Sheets on web) to explore the files.

**Comment by Kpaubert** [comment]
I'll start with mocking and testing. Will you take the GraphQL side of things @FredrikAugust?

**Comment by FredrikAugust** [comment]
Aye aye, captain @Kpaubert!

@IT2901-SINTEF01/backend can I get a "heee-yaaaa"?

Great work as always

**Comment by blauks** [comment]
He-ya

**Comment by FredrikAugust** [comment]
what does this mean, @blauks?

**Comment by FredrikAugust** [comment]
How's the mocking going, Cpt. @Kpaubert?

**Comment by Kpaubert** [comment]
Continuing soon, hopefully finished by the end of the day.
